version: "3"

volumes:
  django_postgres:

services:
  db:
    image: postgres:14.3-alpine
    container_name: "django_movielibrary_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "django_db"
    volumes:
      - django_postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: "django_movielibrary_redis"
    ports:
      - "6379:6379"
